project_id = "ounfqheqtrfxccirkzbp"

[functions.chat]
verify_jwt = false

[functions.feedback]
verify_jwt = true

[functions.ingest-page]
verify_jwt = true

[functions.submit-comment]
verify_jwt = false

[functions.sync-sites-from-sheet]
verify_jwt = true

[functions.submit-survey]
verify_jwt = false

[functions.export-survey]
verify_jwt = false

[functions.submit-data-input]
verify_jwt = false

[functions.export-ggv]
verify_jwt = false

[functions.approve-ggv-export]
verify_jwt = false