export interface SurveyData {
  actorTypes: string[];
  actorTextFields?: Record<string, string>;
  actorOther?: string;
  motivation: string[];
  motivationOther?: string;
  projectTypes: string[];
  contactEmail?: string;
  vnbName?: string;
  projectFocus?: 'ggv' | 'mieterstrom' | 'energysharing';
  ggvProjectType?: 'single' | 'multiple';
  ggvPvSizeKw?: number;
  ggvPartyCount?: number;
  ggvBuildingType?: string;
  ggvBuildingCount?: number;
  ggvAdditionalInfo?: string;
  ggvInOperation?: boolean;
  planningStatus: string[];
  planningStatusOther?: string;
  ggvOrMieterstromDecision?: string;
  ggvDecisionReasons: string[];
  ggvDecisionReasonsOther?: string;
  mieterstromDecisionReasons: string[];
  mieterstromDecisionReasonsOther?: string;
  implementationApproach: string[];
  challenges: string[];
  challengesDetails: Record<string, string>;
  vnbExistingProjects?: string;
  vnbExistingProjectsOther?: string;
  vnbContact: string[];
  vnbContactOther?: string;
  vnbResponse: string[];
  vnbResponseReasons?: string;
  vnbStartTimeline?: string;
  vnbStartTimelineOther?: string;
  vnbAdditionalCosts?: string;
  vnbAdditionalCostsOneTime?: number;
  vnbAdditionalCostsYearly?: number;
  vnbFullService?: string;
  vnbDataProvision?: string;
  vnbDataFormat?: string;
  vnbDataCost?: string;
  vnbDataCostAmount?: number;
  vnbEsaCost?: string;
  vnbEsaCostAmount?: number;
  vnbMsbTimeline?: string;
  vnbRejectionTimeline?: string;
  vnbWandlermessung?: string;
  vnbWandlermessungComment?: string;
  vnbSupportMesskonzept?: string;
  vnbSupportFormulare?: string;
  vnbSupportPortal?: boolean;
  vnbSupportOther?: string;
  vnbInfoAvailable?: string;
  vnbInfoAvailableOther?: string;
  vnbContactHelpful?: string;
  vnbContactHelpfulOther?: string;
  vnbPersonalContacts?: string;
  vnbPersonalContactsOther?: string;
  vnbSupportRating?: number;
  operationStartDate?: string;
  operationVnbDuration?: string;
  operationWandlermessung?: string;
  operationWandlermessungComment?: string;
  operationMsbProvider?: string;
  operationAllocationProvider?: string;
  operationDataProvider?: string;
  operationDataProviderOther?: string;
  operationMsbDuration?: string;
  operationMsbAdditionalCosts?: string;
  operationMsbAdditionalCostsOneTime?: number;
  operationMsbAdditionalCostsYearly?: number;
  operationAllocationWho?: string;
  operationAllocationWhoOther?: string;
  operationDataFormat?: string;
  operationDataFormatOther?: string;
  operationDataCost?: string;
  operationDataCostAmount?: number;
  operationEsaCost?: string;
  operationEsaCostAmount?: number;
  operationSatisfactionRating?: number;
  serviceProviderName?: string;
  serviceProviderRating?: number;
  serviceProviderComments?: string;
  mieterstromProjectType?: string;
  mieterstromPvSizeKw?: number;
  mieterstromPartyCount?: number;
  mieterstromBuildingType?: string;
  mieterstromBuildingCount?: number;
  mieterstromAdditionalInfo?: string;
  mieterstromInOperation?: boolean;
  mieterstromSummenzaehler?: string;
  esStatus: string[];
  esStatusOther?: string;
  esInOperationDetails?: string;
  esOperatorDetails?: string;
  esPlantType: string[];
  esPvSizeKw?: number;
  esWindSizeKw?: number;
  esPartyCount?: number;
  esConsumerTypes: string[];
  esConsumerDetails?: string;
  esVnbContact?: boolean;
  esVnbResponse?: string;
  esVnbResponseOther?: string;
  esInfoSources?: string;
  helpfulInfoSources?: string;
  additionalExperiences?: string;
  surveyImprovements?: string;
  npsScore?: number;
}

export const initialSurveyData: SurveyData = {
  actorTypes: [],
  actorTextFields: {},
  motivation: [],
  projectTypes: [],
  planningStatus: [],
  ggvDecisionReasons: [],
  mieterstromDecisionReasons: [],
  implementationApproach: [],
  challenges: [],
  challengesDetails: {},
  vnbContact: [],
  vnbResponse: [],
  esStatus: [],
  esPlantType: [],
  esConsumerTypes: [],
};
